set number
set laststatus=2
set encoding=utf-8
syntax on
set ignorecase
set smartcase
set wrap linebreak nolist
set hlsearch
set autoindent
set tabstop=4
set shiftwidth=4
set expandtab
set history=1000
set undolevels=1000
set nocompatible
set showmatch
