filetype plugin indent on
let g:airline#extensions#tabline#enabled = 1
let g:airline_powerline_fonts = 1
set autoindent
set backspace=indent,eol,start
set encoding=utf-8
set expandtab
set ffs=unix,dos,mac
set fileencoding=utf-8
set hidden
set history=1000
set hlsearch
set ignorecase
set incsearch
set laststatus=2
set modeline
set nocompatible
set number
set ruler
set shiftround
set shiftwidth=2
set showcmd
set showmatch
set showmode
set smartcase
set softtabstop=0
set tabstop=2
set termbidi
set title
set undolevels=1000
set wrap linebreak nolist
syntax on
